config/routes.rb
Rails.application.routes.draw do
  root 'inventory#all_products'

  get 'product' => 'inventory#one_product'

  get 'category' => 'inventory#by_category'

  get 'new' => 'inventory#new'
  post 'new' => 'inventory#new'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def all_products
  	@products = Product.order(name: :desc)
  end

  def one_product
  	@product = Product.find(params[:id])
  end

  def by_category
  	@category = params[:category]
  	@products = Product.where(category: @category)
  end

	def new
		if params[:name] != nil
			product = Product.create(name: params[:name], price: params[:price], category: params[:category])
			redirect_to product_path(id: product.id)
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventory/_productloop.html.erb
<div class="row">
	<% @products.each do |product| %>
		<div class="col-md-3">
			<div class="well">
				<h3><%= link_to product.name, product_path(id: product.id) %></h3>
				<p><%= number_to_currency product.price %></p>
				<p><%= link_to product.category, category_path(category: product.category) %></p>
				<p><%= link_to "Show", product_path(id: product.id), class: "btn btn-info" %></p>
			</div>
		</div>
	<% end %>
</div>

app/views/inventory/all_products.html.erb
<h1>ALL THE <strong>THINGS!!!</strong></h1>

<%= link_to "Create New Thingie", new_path %>

<%= render 'productloop' %>

app/views/inventory/by_category.html.erb
<div class="well">
<h1>All Piles of our <strong><%= @category %></strong> thingies!!!</h1>
</div>

<%= render 'productloop' %>

app/views/inventory/new.html.erb
<h1>Enter a New Thingie!</h1>

<%= form_tag new_path do %>
	<%= text_field_tag :name, nil, placeholder: "Thingie Name", class: "form-control" %>
	<%= number_field_tag :price, nil, placeholder: "Price", class: "form-control" %>
	<%= text_field_tag :category, nil, placeholder: "Thingie Category", class: "form-control" %>
	<%= submit_tag "Create Product", class: "btn btn-success" %>
<% end %>

app/views/inventory/one_product.html.erb
<div class="well">
<h1><strong><%= @product.name %></strong> thingie!!!</h1>
<p><%= number_to_currency @product.price %></p>
<p>Found in the pile of <%= @product.category %> thingies!</p>
</div>


<%= link_to "GO BACK", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>le Furnistcheur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>

</body>
</html>